### ISSUE TITLE
Monk: Don't create new config files without first checking decerver modules folder

### ISSUE THREAD

**Issue by androlo** [eris-ltd/decerver-modules#8]
https://github.com/eris-ltd/decerver-interfaces/issues/1

I agree. Modules that are run by decerver needs to have their settings and stuff in the decerver folders, not the default ones. I've fixed this for ipfs. The ipfs module will look for the module config in .decerver/modules/ipfs, and then use it to make sure that the config file ipfs uses (with the private key etc.) and the database is stored in .decerver/filesystems/ipfs. Monk and bitcoin should work in the same way. Monk module will probably need a module config file, like the others, where the root folder and other things can be set. Either that or we use default folders for all of them (which is the better choice imo).

**Comment by ebuchman** [comment]
not sure this issue is relevant anymore since everything works out of ~/.decerver.

a default config.json is put in the root dir for each blockchain ie. `~/.decerver/blockchains/thelonious/config.json` and `~/.decerver/blockchains/ethereum/config.json`.  The default is itself written in the source code, not taken from a file, so its already present in the binary. 

When a chain is created/installed, the config is copied into its specifc repo eg `~/.decerver/blockchains/ethereum/5fbac76e.../config.json`, and then read from there at all future points.

**Comment by androlo** [comment]
uh, right... didn't even think of that.
